#
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
#

version: 2
updates:
- directory: "/"
  package-ecosystem: "npm"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: "Asia/Tokyo"
  reviewers:
  - "TakeruUshio"
  ignore:
  - dependency-name: "@types/node"
    update-types: ["version-update:semver-major"]

