name: spec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - run: npm install
      - run: npx playwright test src/static-site1-test.spec.ts
